// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoApi.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Coins", b =>
                {
                    b.Property<int>("MonedaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("MonedaId");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            MonedaId = 1,
                            Descripcion = "Bitcoin",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/674/PNG/512/bitcoin_icon-icons.com_60538.png",
                            Valor = 20.609999999999999
                        },
                        new
                        {
                            MonedaId = 2,
                            Descripcion = "Ethereum",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/3369/PNG/512/ethereum_coin_money_cryptocurrency_icon_210995.png",
                            Valor = 1.1739999999999999
                        },
                        new
                        {
                            MonedaId = 3,
                            Descripcion = "Dogecoin",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/3376/PNG/512/dogecoin_currency_icon_211986.png",
                            Valor = 0.069361000000000006
                        },
                        new
                        {
                            MonedaId = 4,
                            Descripcion = "Pax Dollar",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/2130/PNG/512/pax_cryptocurrency_logo_icon_131411.png",
                            Valor = 1.0011000000000001
                        },
                        new
                        {
                            MonedaId = 5,
                            Descripcion = "EOS",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1386/PNG/512/eos-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95779.png",
                            Valor = 0.95530000000000004
                        },
                        new
                        {
                            MonedaId = 6,
                            Descripcion = "BNB",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1386/PNG/512/bnb-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95846.png",
                            Valor = 231.69999999999999
                        },
                        new
                        {
                            MonedaId = 7,
                            Descripcion = "XRP",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/2130/PNG/512/xrp_cryptocurrency_logo_icon_131379.png",
                            Valor = 0.34234999999999999
                        },
                        new
                        {
                            MonedaId = 8,
                            Descripcion = "Monero",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/3053/PNG/512/monero_wallet_macos_bigsur_icon_189935.png",
                            Valor = 117.566
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
